# Generated by Django 3.1.5 on 2021-02-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
