# Generated by Django 3.1.5 on 2021-02-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0004_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storyapp.story'),
            preserve_default=False,
        ),
    ]
