# Generated by Django 3.1.5 on 2021-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0005_scene_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='location',
            field=models.IntegerField(null=True),
        ),
    ]
