# Generated by Django 3.1.5 on 2021-02-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0006_scene_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ('location',)},
        ),
        migrations.AlterField(
            model_name='scene',
            name='entity_key',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='storyapp.story'),
        ),
    ]
