# Generated by Django 3.1.5 on 2021-02-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyapp', '0007_auto_20210212_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
